Admin\MedicalBundle\Entity\Languages:
    type: entity
    table: languages
    repositoryClass: Admin\MedicalBundle\Entity\LanguagesRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: true
        flag:
            type: text
            nullable: true
        code:
            type: string
            length: 3
            fixed: false
            nullable: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToMany:      
      companies:
        targetEntity: Company
        mappedBy: languagess
    lifecycleCallbacks: 
            prePersist: [ setCreatedAtValue ]
            preUpdate: [ setUpdatedAtValue ]	
