Admin\MedicalBundle\Entity\UserCompanyRequest:
    type: entity
    table: user_company_request
    repositoryClass: Admin\MedicalBundle\Entity\UserCompanyRequestRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstname:
            type: string
            length: '50'
            nullable: true
        lastname:
            type: string
            length: '50'
            nullable: true
        email_address:
            type: string
            length: '100'
            nullable: true
    manyToOne:
      company:
        targetEntity: Company
        inversedBy: usercompanyrequest
        joinColumn:
          name: company_id
          referencedColumnName: id
          onDelete: CASCADE
    lifecycleCallbacks: {  }
