clinic_communication_homepage:
    pattern:  /communications/{quote_id}/{company_id}
    defaults: { _controller: ClinicCommunicationBundle:Default:index, quote_id:null, company_id:null}
clinic_medical_reply:
    pattern:  /clinicreply/{quote_id}/{communication_id}
    defaults: { _controller: ClinicCommunicationBundle:Default:index, quote_id:null, communication_id:null}
clinic_communication_homepage_inner:
    pattern:  /communication/{quote_id}
    defaults: { _controller: ClinicCommunicationBundle:Default:test, quote_id:null}
clinic_medical_login:
    pattern: /login
    defaults: { _controller: ClinicCommunicationBundle:Company:login }
clinic_medical_login_check:
    pattern: /logincheck
    defaults: { _controller: ClinicCommunicationBundle:Company:logincheck }
clinic_medical_logout:
    pattern:  /logout
    defaults: { _controller: ClinicCommunicationBundle:Company:logout}
#clinic_medical_reply:
#    pattern:  /clinicreply/{quote_id}/{communication_id}
#    defaults: { _controller: ClinicCommunicationBundle:Default:clinicreply, communication_id:null}
clinic_medical_reservation:
    pattern:  /reservation
    defaults: { _controller: ClinicCommunicationBundle:Reservation:index}
clinic_medical_reservation_detail:
    pattern:  /reservation/detail/{quote_id}/{company_id}
    defaults: { _controller: ClinicCommunicationBundle:Reservation:reservationdetail}
clinic_medical_changepassword:
    pattern: /changepassword
    defaults: { _controller: ClinicCommunicationBundle:Company:changepassword }
clinic_medical_forgotpassword:
    pattern: /forgotpassword
    defaults: { _controller: ClinicCommunicationBundle:Company:forgotpassword }
clinic_medical_logintemp:
    pattern: /logintemp
    defaults: { _controller: ClinicCommunicationBundle:Default:logintemp }
clinic_medical_places_to_visit:
    pattern:  /visitsplace
    defaults: { _controller: ClinicCommunicationBundle:Default:placestovisit }
clinic_medical_insurance_fund:
    pattern:  /insurancefund
    defaults: { _controller: ClinicCommunicationBundle:Default:insurancefund }
clinic_medical_visatravels:
    pattern:  /visatravels
    defaults: { _controller: ClinicCommunicationBundle:Default:visatravels }
clinic_medical_about:
    pattern:  /about
    defaults: { _controller: ClinicCommunicationBundle:Default:aboutmedical }
clinic_medical_casedispute:
    pattern:  /casedispute
    defaults: { _controller: ClinicCommunicationBundle:Default:casedispute }
clinic_medical_termsofuse:
    pattern:  /termsofuse
    defaults: { _controller: ClinicCommunicationBundle:Default:termsofuse }
clinic_medical_allreviews:
    pattern:  /allreviews
    defaults: { _controller: ClinicCommunicationBundle:Default:allreviews }
clinic_medical_guaranties:
    pattern:  /guaranties
    defaults: { _controller: ClinicCommunicationBundle:Default:guaranties }
clinic_medical_forclinics:
    pattern:  /forclinics
    defaults: { _controller: ClinicCommunicationBundle:Default:forclinics }
clinic_medical_foragencies:
    pattern:  /foragencies
    defaults: { _controller: ClinicCommunicationBundle:Default:foragencies }
clinic_medical_contacts:
    pattern:  /contacts
    defaults: { _controller: ClinicCommunicationBundle:Default:contacts }