parameters:
#    client_medical.example.class: Client\MedicalBundle\Example
#    client_medical.example:
#        class: %client_medical.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
