<?php

namespace Admin\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyVideoRepository extends EntityRepository
{
	/**
     * function saveData
     *
     * @param array   $asData      data
	 * @param integer $snIdCompany company id
	 * @param object  $entity      companyobject
     *
     * @todo   Function to save company wise video
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return boolean
     */
	public function saveData($asData, $snIdCompany, $entity) 
    {
		if(!is_numeric($snIdCompany) || $snIdCompany == '')
            return false;
        
		foreach($asData as $snKey=>$asVal)
		{
			$objCompany = new CompanyVideo();
        
			$objCompany->setCompany($entity);
			$objCompany->setUrl($asVal);
                
			$this->getEntityManager()->persist($objCompany);        
			$this->getEntityManager()->flush();			
		}
		return true;
	}
	
	/**
     * function getVideoDetail
     *     
	 * @param integer $snIdCompany company id	 
     *
     * @todo   Function to get video detail company wise
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return array.
     */
	public function getVideoDetail($snIdCompany)
	{
		return $this->getEntityManager()
            ->createQuery('SELECT c FROM AdminMedicalBundle:CompanyVideo c WHERE c.company = '.$snIdCompany)
            ->getArrayResult(); 
	}
	
	/**
     * function deleteData
     *
     * @param array $asIds array of id
     *
     * @todo   Function to delete video
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return boolean
     */
	public function deleteData($asIds) 
    {
        return $asData = $this->getEntityManager()
            ->createQuery('Delete FROM AdminMedicalBundle:CompanyVideo i where i.id IN ('.$asIds.')')
             ->execute();
    }
}
