<?php

namespace Admin\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagesRepository extends EntityRepository
{
	/**
     * function deleteData
     *
     * @param array  $asIds current culture     
     *
     * @todo   Function to delete languages.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return boolean.
     */
	public function deleteData($asIds) 
    {
        $asData = $this->getEntityManager()
            ->createQuery('Delete FROM AdminMedicalBundle:Languages i where i.id IN ('.$asIds.')')
             ->execute();
		return true;
    }
	
	/**
     * function getLanguageDetail
     *     
     *
     * @todo   Function to get language detail.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return array
     */
	public function getLanguageDetail() 
    {
        return $ssQuery = $this->createQueryBuilder('l')
						->select('l.id,l.name')						
						->orderBy('l.id','DESC')
						->getQuery()						
						->getResult();
    }
}