<?php

namespace Admin\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricesRepository extends EntityRepository
{
	/**
     * function getPricesDetail
     * 
	 * @param integer $snCompanyId companyid.
     *
     * @todo   Function to get prices detail.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return array.
     */
	public function getPricesDetail($snCompanyId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s.id FROM AdminMedicalBundle:Prices s where s.company = '.$snCompanyId.'')
            ->getArrayResult();
    }
}