<?php

namespace Admin\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialofferImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialofferImagesRepository extends EntityRepository
{
	/**
     * function saveData
     *
     * @param string $ssImageName imagename
	 * @param object $entity      entity object
     *
     * @todo   Function save specialoffer images.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return boolean
     */
	 public function saveData($ssImageName, $entity) 
     {
        if($ssImageName == '')
            return false;
        
        $obj = new SpecialofferImages();        
        $obj->setSpecialoffers($entity);
        $obj->setPhoto($ssImageName);                
        $this->getEntityManager()->persist($obj);        
        $this->getEntityManager()->flush();
        return true;
    }
	
	/**
     * function deleteData
     *
     * @param integer $specialId specialofferid
     *
     * @todo   Function delete company detail
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return boolean
     */
	public function deleteData($specialId,$ssFileName) 
    {
		
        return $asData = $this->getEntityManager()
             ->createQuery("Delete FROM AdminMedicalBundle:SpecialofferImages i where i.specialoffers = ".$specialId." and i.photo = '".$ssFileName."' ")
             ->execute();
    }
}