<?php

namespace Admin\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialCouponCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialCouponCodesRepository extends EntityRepository
{
	/**
     * function getAllSpecialOfferCouponCodes
     *
     * @param integer $snId saleid     
     *
     * @todo   Function get all all specialoffer coupon code.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return array
     */
	public function getAllSpecialOfferCouponCodes($snId='')
    {	
		if($snId != '')
		{
			return $ssQuery = $this->createQueryBuilder('scc')
						->select('scc')						
						->where('scc.specialsale = '.$snId)
						->getQuery()						
						->getArrayResult();						
		}
		else
		{
			return array();
		}
	}
}