<?php

namespace Admin\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestimonialvideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialvideoRepository extends EntityRepository
{
	/**
     * function getAllTestimonialVideoDetail
     *           
     *
     * @todo   Function get news detail by date.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return array
     */
    public function getAllTestimonialVideoDetail()
    {
		return $ssQuery = $this->createQueryBuilder('n')
						->select('n')						
						->getQuery()					    
					    ->getArrayResult();
	}
	
	/**
     * function getRandomTestimonial
     *           
     *
     * @todo   Function get random testimonial.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return array
     */
    public function getRandomTestimonial()
    {
		$config = $this->getEntityManager()->getConfiguration();		
		$config->addCustomNumericFunction('RAND', 'DoctrineExtensions\Query\Mysql\Rand');
		return $asData = $this->createQueryBuilder('cmp')							
								 ->addSelect('RAND() as HIDDEN rand')								 
								 ->orderBy('rand')
								 ->setMaxResults(1)
								 ->getQuery()						
								 ->getArrayResult();
	}
	
	/**
     * function deleteData
     *    
	 * @param array $asIds testimonialvideo ids.
     *
     * @todo   Function to delete testimonial.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return boolean
     */
	public function deleteData($asIds) 
    {
        $asData = $this->getEntityManager()
            ->createQuery('Delete FROM AdminMedicalBundle:Testimonialvideo i where i.id IN ('.$asIds.')')
             ->execute();
		return true;
    }
}