<?php

namespace Admin\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserQuoteDocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserQuoteDocumentsRepository extends EntityRepository
{
	/**
     * function deleteData
     *
     * @param  integer $snId field name     
     *
     * @todo   Function to delete user quote documents.
     * @access public
     * @author Arpita Rana <arpita.j.php@gmail.com>
     * @return boolean
     */
    public function deleteData($snId) 
    {        
        return $asData = $this->getEntityManager()
            ->createQuery('Delete FROM AdminMedicalBundle:UserQuoteDocuments i where i.id = '.$snId)
            ->execute();
    }
	
	/**
     * function getCompanyQuotesDocumentsByQuoteDetailId
     *
     * @param integer $snId    user quote detail id	 
     *
     * @todo   Function get documents detail by id.
     * @access public
     * @author Arpita Rana <arpita.j.php@gmail.com>
     * @return array
     */
	 public function getCompanyQuotesDocumentsByQuoteDetailId($snId)
	 {
		return $ssQuery = $this->createQueryBuilder('ucd')
						->select('ucd')
						->where('ucd.userquotedetails = :snId')						
						->setParameter('snId', $snId)
						->getQuery()
						->getArrayResult();
	}
}