<?php

namespace Admin\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
	/**
     * function getActiveCatgoryDetails
     *
     * @param string $status field name     
     *
     * @todo   Function get active category detail.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return boolean
     */
	public function getActiveVideoDetails($status)
	{
		return $asData = $this->getEntityManager()
		->createQuery("SELECT COUNT(c.id) as active_count FROM AdminMedicalBundle:Video c where c.status = '".$status."'")
		->getArrayResult();
	}
	
	/**
     * function deleteData
     *
     * @param array $asIds field name     
     *
     * @todo   Function delete insurance detail
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return boolean
     */
    public function updateVideoStatus($snVideoId, $ssStatus)
    {
        if(is_numeric($snVideoId) && $snVideoId != '')
		{		
			
         return $asData = $this->getEntityManager()
            ->createQuery("update AdminMedicalBundle:Video u set u.status = '".$ssStatus."' where u.id = ".$snVideoId)
            ->execute();
		}
		else
		{
			return false;
		}
    }
	
	/**
     * function getAllNewsCategoryCompanywiseDetail
     *           
     *
     * @todo   Function get news detail by date.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return array
     */
    public function getAllVideoDetail($ssLocale='en')
    {
		return $ssQuery = $this->createQueryBuilder('n')
						->select('n')
						->where('n.status = :ssStatus')
						->setParameter('ssStatus','Active')
						->getQuery()					 
					    ->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker')
					    ->setHint(\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE, $ssLocale)
					    ->getArrayResult();
	}
	
	/**
     * function getAllNewsCategoryCompanywiseDetail
     *           
     *
     * @todo   Function get news detail by date.
     * @access public
     * @author Arpita Jadeja <arpita.j.php@gmail.com>
     * @return array
     */
    public function getAllVideos($ssLocale='en')
    {
		return $ssQuery = $this->createQueryBuilder('n')
						->select('partial n.{id,youtube_url,status}')
						->getQuery()					 
					    ->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker')
					    ->setHint(\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE, $ssLocale)
					    ->getArrayResult();
	}
	
	public function deleteData($asIds) 
    {
        $asData = $this->getEntityManager()
            ->createQuery('Delete FROM AdminMedicalBundle:Video i where i.id IN ('.$asIds.')')
             ->execute();
		return true;
    }
}
